/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Grant
 */
public class MathOperation extends javax.swing.JFrame {

    /**
     * Creates new form MathOperation
     */
    public MathOperation() {
        initComponents();
        lblAddition.setText("");
        lblSubtraction.setText("");
        lblMultiplication.setText("");
        lblDivision.setText("");
        lblExponential.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAddition = new javax.swing.JLabel();
        lblSubtraction = new javax.swing.JLabel();
        lblMultiplication = new javax.swing.JLabel();
        lblDivision = new javax.swing.JLabel();
        lblExponential = new javax.swing.JLabel();
        processButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MATHEMATICAL OPERATIONS");

        lblAddition.setText("jLabel1");

        lblSubtraction.setText("jLabel2");

        lblMultiplication.setText("jLabel3");

        lblDivision.setText("jLabel4");

        lblExponential.setText("jLabel5");

        processButton.setText("Process");
        processButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblExponential)
                                        .addComponent(lblDivision)
                                        .addComponent(lblMultiplication)
                                        .addComponent(lblSubtraction)
                                        .addComponent(lblAddition))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(471, Short.MAX_VALUE)
                                .addComponent(processButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(257, 257, 257)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(lblAddition)
                                .addGap(58, 58, 58)
                                .addComponent(lblSubtraction)
                                .addGap(71, 71, 71)
                                .addComponent(lblMultiplication)
                                .addGap(1, 1, 1)
                                .addComponent(processButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addComponent(lblDivision)
                                .addGap(65, 65, 65)
                                .addComponent(lblExponential)
                                .addContainerGap(152, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void processButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        lblAddition.setText("Addition: 10 + 100 = " + Integer.toString(10 + 100));
        lblSubtraction.setText("Subtraction: 100 - 10 = " + Integer.toString(100 - 10));
        lblMultiplication.setText("Multiplication: 10 * 25 = " + Integer.toString(10 * 25));
        lblDivision.setText("Division: 500 / 100 = " + Integer.toString(500 / 100));
        lblExponential.setText("Exponential: 8 ^ 3 = " + Integer.toString((int) Math.pow(8, 3)));
    }// GEN-LAST:event_processButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MathOperation.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MathOperation.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MathOperation.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MathOperation.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MathOperation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAddition;
    private javax.swing.JLabel lblDivision;
    private javax.swing.JLabel lblExponential;
    private javax.swing.JLabel lblMultiplication;
    private javax.swing.JLabel lblSubtraction;
    private javax.swing.JButton processButton;
    // End of variables declaration//GEN-END:variables
}
