

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Grant
 */
public class StudentDetails extends javax.swing.JFrame {

    /**
     * Creates new form LabSevenGui
     */
    public StudentDetails() {
        initComponents();
        lblStudentOneAddress.setVisible(false);
        lblStudentOneEmail.setVisible(false);
        lblStudentOneName.setVisible(false);
        lblStudentOneID.setVisible(false);
        lblStudentTwoAddress.setVisible(false);
        lblStudentTwoEmail.setVisible(false);
        lblStudentTwoName.setVisible(false);
        lblStudentTwoID.setVisible(false);
        lblStudentThreeAddress.setVisible(false);
        lblStudentThreeEmail.setVisible(false);
        lblStudentThreeName.setVisible(false);
        lblStudentThreeID.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblStudentOneID = new javax.swing.JLabel();
        lblStudentOneName = new javax.swing.JLabel();
        lblStudentOneAddress = new javax.swing.JLabel();
        lblStudentOneEmail = new javax.swing.JLabel();
        studentOneButton = new javax.swing.JButton();
        lblStudentTwoID = new javax.swing.JLabel();
        lblStudentTwoName = new javax.swing.JLabel();
        lblStudentTwoAddress = new javax.swing.JLabel();
        lblStudentTwoEmail = new javax.swing.JLabel();
        studentTwoButton = new javax.swing.JButton();
        lblStudentThreeID = new javax.swing.JLabel();
        lblStudentThreeName = new javax.swing.JLabel();
        lblStudentThreeAddress = new javax.swing.JLabel();
        lblStudentThreeEmail = new javax.swing.JLabel();
        studentThreeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Details");

        lblStudentOneID.setText("jLabel1");

        lblStudentOneName.setText("jLabel2");

        lblStudentOneAddress.setText("jLabel3");

        lblStudentOneEmail.setText("jLabel4");

        studentOneButton.setText("Student 1");
        studentOneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentOneButtonActionPerformed(evt);
            }
        });

        lblStudentTwoID.setText("jLabel5");

        lblStudentTwoName.setText("jLabel6");

        lblStudentTwoAddress.setText("jLabel7");

        lblStudentTwoEmail.setText("jLabel8");

        studentTwoButton.setText("Student 2");
        studentTwoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentTwoButtonActionPerformed(evt);
            }
        });

        lblStudentThreeID.setText("jLabel9");

        lblStudentThreeName.setText("jLabel10");

        lblStudentThreeAddress.setText("jLabel11");

        lblStudentThreeEmail.setText("jLabel12");

        studentThreeButton.setText("Student 3");
        studentThreeButton.setToolTipText("");
        studentThreeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentThreeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblStudentOneEmail)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblStudentTwoEmail))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblStudentOneID)
                            .addGap(212, 212, 212)
                            .addComponent(lblStudentTwoID))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblStudentOneAddress)
                                .addComponent(lblStudentOneName))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblStudentTwoName, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblStudentTwoAddress, javax.swing.GroupLayout.Alignment.TRAILING))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(studentOneButton)
                        .addGap(169, 169, 169)
                        .addComponent(studentTwoButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblStudentThreeID, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblStudentThreeName, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblStudentThreeAddress, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblStudentThreeEmail, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(studentThreeButton))
                .addGap(88, 88, 88))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStudentOneID)
                    .addComponent(lblStudentTwoID)
                    .addComponent(lblStudentThreeID))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStudentOneName)
                    .addComponent(lblStudentTwoName)
                    .addComponent(lblStudentThreeName))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStudentOneAddress)
                    .addComponent(lblStudentTwoAddress)
                    .addComponent(lblStudentThreeAddress))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(lblStudentOneEmail))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStudentTwoEmail)
                            .addComponent(lblStudentThreeEmail))))
                .addGap(99, 99, 99)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentTwoButton)
                    .addComponent(studentThreeButton)
                    .addComponent(studentOneButton))
                .addContainerGap(129, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studentOneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentOneButtonActionPerformed
        // TODO add your handling code here:
        lblStudentOneID.setText("126373949");
        lblStudentOneID.setVisible(true);
        lblStudentOneName.setText("Grant Hartley");
        lblStudentOneName.setVisible(true);
        lblStudentOneEmail.setText("ghartley@una.edu");
        lblStudentOneEmail.setVisible(true);
        lblStudentOneAddress.setText("123 Main Street");
        lblStudentOneAddress.setVisible(true);
    }//GEN-LAST:event_studentOneButtonActionPerformed

    private void studentTwoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentTwoButtonActionPerformed
        // TODO add your handling code here:
        lblStudentTwoID.setText("126373949");
        lblStudentTwoID.setVisible(true);
        lblStudentTwoName.setText("Helping Hartley");
        lblStudentTwoName.setVisible(true);
        lblStudentTwoEmail.setText("helping@una.edu");
        lblStudentTwoEmail.setVisible(true);
        lblStudentTwoAddress.setText("123 Main Street");
        lblStudentTwoAddress.setVisible(true);
    }//GEN-LAST:event_studentTwoButtonActionPerformed

    private void studentThreeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentThreeButtonActionPerformed
        // TODO add your handling code here:
        lblStudentThreeID.setText("1263732389");
        lblStudentThreeID.setVisible(true);
        lblStudentThreeName.setText("Help Hartley");
        lblStudentThreeName.setVisible(true);
        lblStudentThreeEmail.setText("help@una.edu");
        lblStudentThreeEmail.setVisible(true);
        lblStudentThreeAddress.setText("123 Main Street");
        lblStudentThreeAddress.setVisible(true);
    }//GEN-LAST:event_studentThreeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblStudentOneAddress;
    private javax.swing.JLabel lblStudentOneEmail;
    private javax.swing.JLabel lblStudentOneID;
    private javax.swing.JLabel lblStudentOneName;
    private javax.swing.JLabel lblStudentThreeAddress;
    private javax.swing.JLabel lblStudentThreeEmail;
    private javax.swing.JLabel lblStudentThreeID;
    private javax.swing.JLabel lblStudentThreeName;
    private javax.swing.JLabel lblStudentTwoAddress;
    private javax.swing.JLabel lblStudentTwoEmail;
    private javax.swing.JLabel lblStudentTwoID;
    private javax.swing.JLabel lblStudentTwoName;
    private javax.swing.JButton studentOneButton;
    private javax.swing.JButton studentThreeButton;
    private javax.swing.JButton studentTwoButton;
    // End of variables declaration//GEN-END:variables
}
